### ISSUE TITLE
Bad performance on mobile devices because of blurred background

### ISSUE THREAD

**Issue by AgentSmith0** [vidstack/vidstack.io#2]
On mobile devices the framerate drops dramtically and the website is barely unusable, because of the blurred background when opening the sidebar...

**Comment by mihar-22** [comment]
That's strange, we haven't run in to that issue in any of our testing (used few different devices). What Phone/OS+Version/Browser+Version are you using?

**Comment by AgentSmith0** [comment]
It seems to be a problem with the browser I was using, every other "normal" browser works fine. Thanks!
